"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'honda'? I predict False.");
console.log(car == 'honda');
console.log("Is car != 'toyota'? I predict True.");
console.log(car != 'toyota');
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru');
console.log("Is car.length < 10? I predict True.");
console.log(car.length < 10);
console.log("Is car.length > 5? I predict True.");
console.log(car.length > 5);
console.log("Is car.startsWith('s')? I predict True.");
console.log(car.startsWith('s'));
console.log("Is car.includes('b')? I predict True.");
console.log(car.includes('b'));
console.log("Is car.toUpperCase() === 'SUBARU'? I predict True.");
console.log(car.toUpperCase() === 'SUBARU');
